### ISSUE TITLE
installer errors

### ISSUE THREAD

**Issue by crazyjoery** [rappasoft/laravel-boilerplate-installer#1]
Everything runs fine until the migrations after that i get the following.

> PHP Fatal error:  Class 'Rappasoft\BoilerplateInstaller\Installation\SetAdministratorAccount' not found in /home/vagrant/.composer/vendor/rappasoft/laravel-boilerplate-installer/src/NewCommand.php on line 106
PHP Stack trace:
PHP   1. {main}() /home/vagrant/.composer/vendor/rappasoft/laravel-boilerplate-installer/boilerplate:0
PHP   2. Symfony\Component\Console\Application->run() /home/vagrant/.composer/vendor/rappasoft/laravel-boilerplate-installer/boilerplate:16
PHP   3. Symfony\Component\Console\Application->doRun() /home/vagrant/.composer/vendor/symfony/console/Application.php:126
PHP   4. Symfony\Component\Console\Application->doRunCommand() /home/vagrant/.composer/vendor/symfony/console/Application.php:195
PHP   5. Symfony\Component\Console\Command\Command->run() /home/vagrant/.composer/vendor/symfony/console/Application.php:878
PHP   6. Rappasoft\BoilerplateInstaller\NewCommand->execute() /home/vagrant/.composer/vendor/symfony/console/Command/Command.php:259

> Fatal error: Class 'Rappasoft\BoilerplateInstaller\Installation\SetAdministratorAccount' not found in /home/vagrant/.composer/vendor/rappasoft/laravel-boilerplate-installer/src/NewCommand.php on line 106

> Call Stack:
    0.0001     226352   1. {main}() /home/vagrant/.composer/vendor/rappasoft/laravel-boilerplate-installer/boilerplate:0
    0.0265    1914016   2. Symfony\Component\Console\Application->run() /home/vagrant/.composer/vendor/rappasoft/laravel-boilerplate-installer/boilerplate:16
    0.0326    2258680   3. Symfony\Component\Console\Application->doRun() /home/vagrant/.composer/vendor/symfony/console/Application.php:126
    0.0327    2259600   4. Symfony\Component\Console\Application->doRunCommand() /home/vagrant/.composer/vendor/symfony/console/Application.php:195
    0.0327    2260104   5. Symfony\Component\Console\Command\Command->run() /home/vagrant/.composer/vendor/symfony/console/Application.php:878
    0.0329    2264256   6. Rappasoft\BoilerplateInstaller\NewCommand->execute() /home/vagrant/.composer/vendor/symfony/console/Command/Command.php:259

After setting up the UserTableSeeder.php file with the proper admin credentials i get the following when trying to seed the database:

> vagrant@homestead:~/Code/lonestar$ php artisan db:seed
Seeded: UserTableSeeder
Seeded: RoleTableSeeder
PHP Fatal error:  Class 'App\Models\Access\User\User' not found in /home/vagrant/Code/lonestar/database/seeds/Access/UserRoleSeeder.php on line 28
PHP Stack trace:
PHP   1. {main}() /home/vagrant/Code/lonestar/artisan:0
PHP   2. Illuminate\Foundation\Console\Kernel->handle() /home/vagrant/Code/lonestar/artisan:36
PHP   3. Symfony\Component\Console\Application->run() /home/vagrant/Code/lonestar/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:107
PHP   4. Symfony\Component\Console\Application->doRun() /home/vagrant/Code/lonestar/vendor/symfony/console/Application.php:117
PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/vagrant/Code/lonestar/vendor/symfony/console/Application.php:186
PHP   6. Illuminate\Console\Command->run() /home/vagrant/Code/lonestar/vendor/symfony/console/Application.php:791
PHP   7. Symfony\Component\Console\Command\Command->run() /home/vagrant/Code/lonestar/vendor/laravel/framework/src/Illuminate/Console/Command.php:155
PHP   8. Illuminate\Console\Command->execute() /home/vagrant/Code/lonestar/vendor/symfony/console/Command/Command.php:256
PHP   9. Illuminate\Container\Container->call() /home/vagrant/Code/lonestar/vendor/laravel/framework/src/Illuminate/Console/Command.php:169
PHP  10. call_user_func_array:{/home/vagrant/Code/lonestar/vendor/laravel/framework/src/Illuminate/Container/Container.php:507}() /home/vagrant/Code/lonestar/vendor/laravel/framework/src/Illuminate/Container/Container.php:507
PHP  11. Illuminate\Database\Console\Seeds\SeedCommand->fire() /home/vagrant/Code/lonestar/vendor/laravel/framework/src/Illuminate/Container/Container.php:507
PHP  12. Illuminate\Database\Eloquent\Model::unguarded() /home/vagrant/Code/lonestar/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php:64
PHP  13. Illuminate\Database\Console\Seeds\SeedCommand->Illuminate\Database\Console\Seeds\{closure}() /home/vagrant/Code/lonestar/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:2297
PHP  14. DatabaseSeeder->run() /home/vagrant/Code/lonestar/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php:63
PHP  15. Illuminate\Database\Seeder->call() /home/vagrant/Code/lonestar/database/seeds/DatabaseSeeder.php:19
PHP  16. AccessTableSeeder->run() /home/vagrant/Code/lonestar/vendor/laravel/framework/src/Illuminate/Database/Seeder.php:39
PHP  17. Illuminate\Database\Seeder->call() /home/vagrant/Code/lonestar/database/seeds/AccessTableSeeder.php:16
PHP  18. UserRoleSeeder->run() /home/vagrant/Code/lonestar/vendor/laravel/framework/src/Illuminate/Database/Seeder.php:39

**Comment by rappasoft** [comment]
Thats my bad.

Do a global composer update and a dump autoload and try again. Should work.

**Comment by crazyjoery** [comment]
okay i am able to fill out the admin credentials now through the installer. After that it asks to seed the database and gives the following:

> Would you like to seed the database? (yes/no) [yes]:
> 
> Seeded: UserTableSeeder
> Seeded: RoleTableSeeder
> PHP Fatal error:  Class 'App\Models\Access\User\User' not found in /home/vagrant/Code/lonestar/database/seeds/Access/UserRoleSeeder.php on line 28
> PHP Stack trace:
> PHP   1. {main}() /home/vagrant/Code/lonestar/artisan:0
> PHP   2. Illuminate\Foundation\Console\Kernel->handle() /home/vagrant/Code/lonestar/artisan:36
> PHP   3. Symfony\Component\Console\Application->run() /home/vagrant/Code/lonestar/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:107
> PHP   4. Symfony\Component\Console\Application->doRun() /home/vagrant/Code/lonestar/vendor/symfony/console/Application.php:117
> PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/vagrant/Code/lonestar/vendor/symfony/console/Application.php:186
> PHP   6. Illuminate\Console\Command->run() /home/vagrant/Code/lonestar/vendor/symfony/console/Application.php:791
> PHP   7. Symfony\Component\Console\Command\Command->run() /home/vagrant/Code/lonestar/vendor/laravel/framework/src/Illuminate/Console/Command.php:155
> PHP   8. Illuminate\Console\Command->execute() /home/vagrant/Code/lonestar/vendor/symfony/console/Command/Command.php:256
> PHP   9. Illuminate\Container\Container->call() /home/vagrant/Code/lonestar/vendor/laravel/framework/src/Illuminate/Console/Command.php:169
> PHP  10. call_user_func_array:{/home/vagrant/Code/lonestar/vendor/laravel/framework/src/Illuminate/Container/Container.php:507}() /home/vagrant/Code/lonestar/vendor/laravel/framework/src/Illuminate/Container/Container.php:507
> PHP  11. Illuminate\Database\Console\Seeds\SeedCommand->fire() /home/vagrant/Code/lonestar/vendor/laravel/framework/src/Illuminate/Container/Container.php:507
> PHP  12. Illuminate\Database\Eloquent\Model::unguarded() /home/vagrant/Code/lonestar/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php:64
> PHP  13. Illuminate\Database\Console\Seeds\SeedCommand->Illuminate\Database\Console\Seeds\{closure}() /home/vagrant/Code/lonestar/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:2297
> PHP  14. DatabaseSeeder->run() /home/vagrant/Code/lonestar/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php:63
> PHP  15. Illuminate\Database\Seeder->call() /home/vagrant/Code/lonestar/database/seeds/DatabaseSeeder.php:19
> PHP  16. AccessTableSeeder->run() /home/vagrant/Code/lonestar/vendor/laravel/framework/src/Illuminate/Database/Seeder.php:39
> PHP  17. Illuminate\Database\Seeder->call() /home/vagrant/Code/lonestar/database/seeds/AccessTableSeeder.php:16
> PHP  18. UserRoleSeeder->run() /home/vagrant/Code/lonestar/vendor/laravel/framework/src/Illuminate/Database/Seeder.php:39
> 
> 
>   [Symfony\Component\Debug\Exception\FatalErrorException]
>   Class 'App\Models\Access\User\User' not found
> 
> 
> 
> 
>   [Symfony\Component\Process\Exception\ProcessFailedException]
>   The command "php artisan db:seed" failed.
>   Exit Code: 255(Unknown error)
>   Working directory: /home/vagrant/Code/lonestar
>   Output:
>   ================
>   Error Output:
>   ================
> 
> 
> new [<name>]

**Comment by rappasoft** [comment]
Weird, works for me. You on homestead?

**Comment by rappasoft** [comment]
Question, did you change the namespace when it asked or kept it as default?

**Comment by crazyjoery** [comment]
Running the latest homestead revision and indeed changed the namespace.

**Comment by rappasoft** [comment]
I'm thinking maybe the namespace doesn't change all the spots correctly.

**Comment by crazyjoery** [comment]
Could be the case ill try another install without namespace changes

**Comment by crazyjoery** [comment]
without setting a namespace it runs just fine without any errors indeed. It appears to only be the user model that doesn't get it's namespace changed when called for as that is still calling for the App namespace.

**Comment by rappasoft** [comment]
Fixed: https://github.com/rappasoft/laravel-boilerplate-installer/commit/7a1b5592c35be6731df004c02d6ce286f022aaf7
