### ISSUE TITLE
Config not updated when namespace is changed from App during install

### ISSUE THREAD

**Issue by CoeusCC** [rappasoft/laravel-boilerplate-installer#3]
I don't know if this is actually an issue that could be resolved during installation or simply something that needs to be noted for users to do themselves, but when changing the default namespace (App) everything seems to work fine until you hit a route that touches the config files. For me it was my initial login and I found the following entries in the related config files:
- [root]\config\access.php:
   13:     'role' => App\Models\Access\Role\Role::class,
   ..
   24:     'permission' => App\Models\Access\Permission\Permission::class,

- [root]\config\auth.php:
   68          'users' => [
   69              'driver' => 'eloquent',
   70:             'model' => App\Models\Access\User\User::class,
   71          ],
- [root]\config\datatables.php:
   68:         'model' => 'App\Models',

- [root]\config\services.php:
   36      'stripe' => [
   37:         'model'  => App\Models\Access\User\User::class,
   38          'key'    => env('STRIPE_KEY'),
   39          'secret' => env('STRIPE_SECRET'),

There were also a few in comments and other locations such as tests, but I'm not sure if it would be feasible or desirable to address them all. Here's a list of files for reference, but I've omitted the location for brevity:

- [root]\database\seeds\Access\PermissionRoleSeeder.php:
- [root]\vendor\hieu-le\active\tests\ActiveTest.php:
- [root]\vendor\laracasts\generators\readme.md:
- [root]\vendor\laracasts\generators\src\stubs\seed.stub:
- [root]\vendor\laravel\socialite\readme.md:
- [root]\vendor\mockery\mockery\docs\cookbook\mocking_hard_dependencies.rst:
- [root]\vendor\phpspec\prophecy\README.md:

**Comment by rappasoft** [comment]
Hmm I wonder if the underlying functionality in the namespace change function is only looking for "namespaces" and not just class calls.

**Comment by rappasoft** [comment]
Anything in the vendor folder i'm not going to touch, they shouldn't have anything to do with it. I'm going to append to the class to fix those files.

**Comment by rappasoft** [comment]
Fixed thanks!: https://github.com/rappasoft/laravel-boilerplate-installer/commit/eb7e2845edfd93aa37b7d9d85648c5b5e9bb22ef
